package com.example.neckguard

object NotificationPool {
    val badPostureMessages = listOf(
        "Your desk is not your enemy. Your posture is.",
        "Your body is flagging something. Don't table it like a low-priority task.",
        "That posture is not reflecting the standard you hold everything else to.",
        "Your shoulders are slowly becoming earrings.",
        "Neck position needs attention.",
        "Your output is high. Your spinal load shouldn't have to match it.",
        "Tiny adjustment. Big difference.",
        "You've drifted. Gently come back.",
        "Peak performers don't ignore posture.",
        "System error: postural efficiency below threshold.",
        "Your posture just filed a formal complaint.",
        "Raise the screen. Lower the tension.",
        "Even casual use deserves better than that angle.",
        "You're starting to slouch.",
        "That's a posture your chiropractor would screenshot.",
        "Your body has enough to deal with already.",
        "Quick reset recommended.",
        "Your posture just dropped below acceptable levels.",
        "Strong posture. Strong presence.",
        "You're absorbed in the book. Your spine would like to be absorbed too — into better alignment.",
        "Let's make today a little easier.",
        "A gentle correction can go a long way.",
        "Check in with your body. It's been waiting.",
        "Let's survive exams without collecting extra pain.",
        "Academic pressure detected. Posture pressure too.",
        "You're building a career, not neck tension.",
        "Time to upgrade your sitting position.",
        "That's a forward head position looking for trouble.",
        "You've been in that position long enough to notice it. Now change it.",
        "Your competition is probably sitting straighter.",
        "Give your body a fighting chance.",
        "Let's create a little more space to breathe.",
        "Let's get back to optimal.",
        "Leaders optimize every variable. This one is overdue.",
        "Quick adjustment. Maximum return.",
        "Cramming hurts less when your neck isn't also cramping.",
        "Bring comfort back into your study session.",
        "Your neck just texted. It's not happy.",
        "Your posture fell off. No shame. Just fix it.",
        "Alignment can be improved.",
        "Even five seconds of good posture counts. Start there.",
        "Your productivity system has a gap. It's called posture.",
        "Bring your shoulders back and stay in command.",
        "Ease into better alignment.",
        "Posture check before the next caffeine refill.",
        "Your shoulders have crept up to somewhere near your earlobes.",
        "A comfortable posture supports better focus.",
        "Bestie, your neck called. It's not okay.",
        "You're two chapters away from a very uncomfortable tomorrow.",
        "You deserve a more comfortable position.",
        "Your posture is on do-not-disturb. Override it.",
        "Quick reset. High performance starts with good alignment.",
        "Your body is part of your productivity system.",
        "Your body may need a small adjustment.",
        "Exam pressure is real. Extra muscle tension is optional.",
        "The work can wait two breaths. Your spine cannot.",
        "Chin up. Literally.",
        "We're rooting for you. Your posture is not rooting for you right now.",
        "Comfort begins with alignment.",
        "You're working on your mind. Don't forget the structure holding it up.",
        "Your neck would like to file a complaint.",
        "Your body is part of the system.",
        "Your posture deserves the same attention as your work.",
        "The deadline is in three hours. Your posture can't afford another crisis.",
        "Optimization opportunity detected.",
        "Straighten up. Future you is watching.",
        "Precision matters.",
        "That position is delightful until it isn't. Adjust before the line is crossed.",
        "A quick recalibration before the next block of high-stakes work.",
        "Check your posture before continuing.",
        "Realign. Not because you failed — because you noticed.",
        "Your body has been speaking softly for a while now. It's starting to speak louder.",
        "That study position has quietly declared war on your neck.",
        "Pause. Adjust. Continue.",
        "You're focused on results. Don't forget your posture.",
        "Your body already has a full-time job keeping up with you. Don't make it harder.",
        "Your reading nook is gorgeous. Your posture in it is not.",
        "A mindful reset might help right now.",
        "Your neck could use a break.",
        "Recalibrate and continue.",
        "That's a posture that's been compensating for exhaustion. Sit it up.",
        "You wouldn't ghost a friend sending distress signals. Don't ghost your body.",
        "Comfort is a performance metric. You're underperforming it.",
        "Your posture is telling you something your schedule refuses to.",
        "Your body is on your team. Help it out.",
        "Your body language is speaking before you do. Adjust it.",
        "Cozy can still have good spinal support. Seek that version.",
        "Structural misalignment creates downstream performance costs. Correct it.",
        "Decision-makers don't operate from a forward head posture.",
        "Your body is in its villain era right now. Redirect it.",
        "Pause and realign.",
        "Your shoulders seem to be carrying extra tension.",
        "Hustle culture didn't budget for chronic neck pain. Adjust now.",
        "Ease back into alignment.",
        "Stress is already expensive. Don't let bad posture add to the bill.",
        "You wouldn't let your friends slouch like that. Don't let yourself either.",
        "Real self-care includes sitting correctly. Just saying.",
        "You're leaning more than usual.",
        "That's a position your spine is tolerating, not enjoying.",
        "Better posture. Better output.",
        "Check in with yourself for a moment.",
        "The tension in your neck is compounding interest.",
        "Plot twist: sitting up straight is actually the power move.",
        "A small adjustment may help.",
        "Work from a place that feels steady, not strained.",
        "What would a comfortable version of this position feel like? Find it.",
        "Learning is easier when you're comfortable.",
        "Reposition for better comfort.",
        "Your back is asking for support.",
        "Quick realignment before the next thing on the list.",
        "Your back didn't sign up for this semester.",
        "Settle in properly. Your body deserves coziness and comfort both.",
        "Fatigue and bad posture are a package deal. Break one up.",
        "High performance requires strong foundations.",
        "That forward lean is giving villain origin story. Fix it.",
        "Efficiency starts with alignment.",
        "You know better. Your posture is testing that.",
        "The pitch is polished. The posture needs work.",
        "Okay but what if you sat up and glowed simultaneously?",
        "Your neck is negotiating terms your spine didn't agree to.",
        "Sit tall and continue.",
        "Let's not give that pain any extra help today.",
        "A quick posture pause may help.",
        "Your posture fell off harder than your situationship.",
        "Sit up before the scroll hole gets deeper.",
        "A tiny reset can go a long way.",
        "Presence starts in the body. Come back to yours.",
        "Success is easier when your neck isn't fighting you.",
        "Let's reduce some tension.",
        "Your spine has seen better scroll sessions.",
        "A small correction now may help later.",
        "You've revised the essay three times. Now revise your posture once.",
        "Bring awareness back to your body.",
        "Soft setting, stiff neck. Let's fix the second one.",
        "Your neck deserves some kindness.",
        "You're one adjustment away from better alignment.",
        "The deadline is scary. This posture is scarier.",
        "Your body is asking for attention.",
        "Your back just left you on read. Time to reply.",
        "Give your spine the study break it deserves.",
        "Main character energy doesn't include a forward head posture.",
        "Let your posture support your work.",
        "Posture check.",
        "Your pillow fortress has compromised your cervical spine.",
        "Your shoulders have drifted forward.",
        "Your posture is below peak performance.",
        "That study position has seen better days.",
        "You push through everything. Push through a quick realignment too.",
        "That's a position built for urgency, not sustainability.",
        "The blanket is perfect. The neck angle is not.",
        "That screen distance is doing your eyes and your neck zero favors.",
        "Great atmosphere. Less great axial loading on your cervical spine.",
        "The all-nighter is optional. The neck pain is becoming mandatory.",
        "Five seconds now will cost you less than five physio sessions later.",
        "That forward head position is adding 10lbs of load to your cervical spine. Inefficient.",
        "Your body is offering useful feedback.",
        "Premium habits start here.",
        "That tension you're ignoring is taking notes.",
        "The content isn't worth the cervical strain. Adjust first.",
        "Ambition runs straighter than that.",
        "Check where your head has traveled to. Bring it home.",
        "You've sunk into something your back won't appreciate later.",
        "The grind doesn't stop. Your posture correction can start.",
        "Curled into something that looked better than it feels.",
        "Let's reduce some unnecessary strain.",
        "That scroll position is going to feel real different tomorrow morning.",
        "Your posture needs a quick tune-up.",
        "Your body did not consent to this position.",
        "Refine the details.",
        "Protect your energy.",
        "Consider this a performance optimization alert.",
        "You've been leaning for a while now.",
        "Your neck has entered its struggle era.",
        "Sit up before your textbook wins.",
        "Quick posture reset before the next panic session.",
        "Sit taller. Think clearer. It's not a myth.",
        "You're one adjustment away from looking and feeling sharper.",
        "You're running on too little sleep and too much forward lean.",
        "Productivity lost to discomfort is productivity lost for good.",
        "Your spine has been patient. It's running out of patience.",
        "Something in your alignment is asking for attention. Let it have it.",
        "Your cervical spine is not a stress ball.",
        "Your chair has a back. Use it.",
        "Your output metrics are strong. Your ergonomic metrics are not.",
        "You're doing the work. Give your body a small assist.",
        "Posture audit: action required.",
        "Your notes need attention. So does your posture.",
        "Small adjustment. Big professional energy.",
        "You've optimized your calendar. Now optimize your spine.",
        "You've built strong systems. This one needs an upgrade.",
        "Take a moment to sit comfortably.",
        "Time to stop becoming one with the desk.",
        "The tea is warm. Let's get the posture warm too.",
        "Discipline extends to the body. Apply it here.",
        "You're that girl/that guy. Act like it. Sit up.",
        "Quick alignment check before the next task.",
        "Main character energy does not live in a forward head posture.",
        "You've melted into the furniture. Time to unmelted.",
        "You've audited everything except the position you make decisions from.",
        "Quick realignment suggested.",
        "Stay sharp. Sit sharp.",
        "The hustle can wait five seconds.",
        "You're leaving performance on the table. Literally.",
        "Cozy shouldn't mean compressed. Find the balance.",
        "Your shoulders look tired.",
        "The book isn't going anywhere. Sit up and enjoy it properly.",
        "Rebalance before continuing.",
        "You've been at this angle for a while now.",
        "Your spine is studying harder than you are right now.",
        "Lengthen your spine and soften your shoulders.",
        "Adjustment recommended.",
        "Sit tall and stay cozy.",
        "Five seconds now can save discomfort later.",
        "A top performer takes care of the basics.",
        "Your shoulders are braced for impact. There's no impact coming. Soften them.",
        "Babe. The slouch. We need to talk.",
        "That's a lot of load on a spine that has decades ahead of it.",
        "Your notes are scattered. Your spine doesn't have to be too.",
        "Your spine is carrying more than your notes right now.",
        "Your textbook doesn't need to be that close to your face.",
        "The screen will still be there. Take the moment to reset.",
        "Consider this a corrective action item.",
        "That's a position your future self will remember uncomfortably.",
        "Your input quality is high. Your physical infrastructure is lagging.",
        "Confidence looks better upright.",
        "Don't let tension pile up.",
        "Your body is communicating clearly. The message is: sit up.",
        "Your posture is the weakest variable in an otherwise high-performing setup.",
        "The boardroom reads body language. Yours is currently off-brief.",
        "Your body is begging for a tiny adjustment.",
        "Your sitting position has slowly stopped supporting you.",
        "Tension held in the body becomes tension carried through the day.",
        "We like you. Your neck angle? Less so.",
        "Brief posture correction needed.",
        "The assignment is difficult enough. Don't add neck pain.",
        "Your shoulders seem a little tense.",
        "A small adjustment may bring more comfort.",
        "Relax your shoulders and reset.",
        "Time for a performance upgrade.",
        "Recalibrate before the next task demands everything you have.",
        "Quick reset before the tension builds.",
        "Upgrade your position.",
        "Quick fix: shoulders back, chin level, continue scrolling.",
        "A gentle correction is all you need.",
        "A softer posture starts with awareness.",
        "Correct now. You don't have time for a physiotherapist later.",
        "You wouldn't accept underperformance in a team member. Don't accept it here.",
        "Executive function benefits from physical alignment. Get back to baseline.",
        "Straighten up. Leaders don't operate from a slump.",
        "That tilt has been going on long enough.",
        "Your neck is basically a bookmark right now. Unfold it.",
        "Your chair is winning right now. Take it back.",
        "The reading light is warm. The neck strain is not.",
        "Time to straighten up.",
        "Your next productivity boost starts with posture.",
        "Your body is your longest-running work tool. Treat it accordingly.",
        "There's a version of this task that doesn't cost you tension. Start there.",
        "Sit a little straighter.",
        "Notice the tension. Then release it.",
        "Pause and reconnect with your posture.",
        "Your posture is falling behind your ambition.",
        "Your physical operating condition has dropped below acceptable parameters.",
        "Not to be dramatic but your spine is crying and we felt that.",
        "Every top performer has a reset ritual. This is yours.",
        "You've been serving looks but your posture is not serving anything right now.",
        "Your future self just sent a strongly worded message. It said: sit up.",
        "The meeting is in ten minutes. Your posture isn't ready.",
        "Your posture has drifted away from where it felt good. Guide it back.",
        "You're absorbing information and absorbing tension simultaneously.",
        "Better posture starts now.",
        "The aesthetic is there. The spinal alignment is not.",
        "The vibe is immaculate. The posture is not. Easy fix.",
        "Take a gentle moment to realign.",
        "Posture check. Back to peak efficiency.",
        "Your breath has shortened. Your posture may be why.",
        "Slouching won't improve the grade, unfortunately.",
        "Your setup needs a quick refinement.",
        "Brief correction before the next video autoplay.",
        "Your posture needs attention.",
        "The strain is quiet now. It won't be later.",
        "You've earned rest. In the meantime, earn better posture.",
        "That position is not it and somewhere you already know that.",
        "Head position moving forward.",
        "That slump is costing you presence you can't bill back.",
        "The slump is not the aesthetic. You know this.",
        "Notice what you're holding. Then choose to release it.",
        "A mindful worker checks in with the body, not just the task list.",
        "Your body wrote a footnote: sit up.",
        "That's not a vibe. That's a spasm waiting.",
        "Protecting your energy includes protecting your neck.",
        "Time to ease some strain.",
        "Every decision made from poor posture is a slightly degraded decision.",
        "That angle is giving warranty void. Correct it.",
        "You've been leaning into this problem. Literally. Stop.",
        "That tension in your upper back has been building shift by shift.",
        "Comfort and alignment aren't opposites. Find the overlap.",
        "Return to a position that feels balanced.",
        "That's a lot of tension for someone who deserves to feel good.",
        "That's a posture that's going to show up in your 30s and demand answers.",
        "Quick reset. Then back to academic chaos.",
        "You've sunk into softness in all the wrong ways.",
        "A gentle posture reset might help.",
        "Your neck is carrying workload that isn't in your job description.",
        "Your wellness routine deserves a better physical foundation than this.",
        "High output requires high maintenance. Start with alignment.",
        "You've been in this position since before you noticed. That's how it always starts.",
        "Tech neck is a thing. You're doing the thing.",
        "Posture drifting detected.",
        "Take care of yourself while you learn.",
        "Take a breath and sit a little taller.",
        "Check in with your posture.",
        "Give your body the same attention as your tasks.",
        "The phone can come up. Your neck doesn't need to go down.",
        "Your body gave you a sign. You're going to want to read it.",
        "The discomfort you're ignoring is compiling quietly in the background.",
        "Small correction. Big impact.",
        "The details separate category leaders from the rest. This is one of them.",
        "Notice where your body is asking for support.",
        "Time for a quick adjustment.",
    )
    
    val goodPostureMessages = listOf(
        "No strain detected. Carry on.",
        "That's a sustainable study position.",
        "Keep going.",
        "Nice consistency.",
        "Soft focus. Strong spine. That's the cozy academic ideal.",
        "That's a posture worth maintaining.",
        "Steady alignment through a high-stress session. That's discipline.",
        "That's called protecting your long game.",
        "Less strain. More capacity. That's the trade you just made.",
        "Your body seems comfortable and supported.",
        "Good idle posture. Underrated skill.",
        "That's a habit your future self will bring up in therapy as a win.",
        "Excellent form. Carry that into the next hour.",
        "Looking steady.",
        "Aligned. Unbothered. Hydrated (we hope). Thriving.",
        "Looking optimized.",
        "Comfortable enough to stay. Alert enough to absorb. That's the goal.",
        "That's a habit worth building.",
        "Your nervous system just got a little relief. You did that.",
        "Your physical presence is as refined as your strategy.",
        "Nice balance between focus and comfort.",
        "That's looking much better.",
        "That's giving longevity. Your 40-year-old self is screaming thank you.",
        "That's how sustainable studying looks.",
        "Strong and sustainable.",
        "That's a posture streak worth keeping.",
        "Your posture is as considered as your reading list.",
        "That's a sustainable position, which is more than can be said for your schedule.",
        "You're holding it together — literally and figuratively.",
        "Smart student. Smart posture.",
        "Your posture is matching your potential.",
        "Elite habits are forming.",
        "Soft life, strong spine. You cracked the code.",
        "That's the posture behind the performance.",
        "Keep that gentle consistency going.",
        "That's what healthy device use actually looks like.",
        "Soft shoulders. Clear mind. Good work.",
        "Your spine just got a grade A.",
        "That's a conscious, comfortable position. You chose it. It counts.",
        "Great alignment. Great momentum.",
        "There's nothing to fix right now. Just maintain.",
        "You held it. That matters more than it sounds.",
        "Precise. Controlled. Exactly on spec.",
        "Great posture.",
        "That's a win inside a long and heavy day.",
        "Strong habits in action.",
        "You're making good posture look effortless.",
        "Well maintained.",
        "You're supporting your body well.",
        "This is what working without self-inflicting harm looks like.",
        "Sitting right, living right. The checklist is getting checked.",
        "That's a habit that's quietly protecting you.",
        "Every small win counts.",
        "Aligned and going. Keep it exactly like this.",
        "Keep nurturing those healthy habits.",
        "You're investing in longevity while others are just investing in deadlines.",
        "Aligned and focused. The notes are going in.",
        "Your neck thanks you.",
        "You're moving through work with intention.",
        "Aligned. Grounded. Present. That's real wellness.",
        "Small choices, meaningful impact.",
        "Okay you're sitting right and we're a little obsessed.",
        "Looking calm, aligned, and focused.",
        "Warm setting. Warm posture approval.",
        "You're making this semester easier on yourself.",
        "You're building the habit even on the hard days. That's when it counts most.",
        "Your body seems happy there.",
        "You're at ease and well-positioned. Both things at once.",
        "Ease and focus existing together. That's what you're after.",
        "You're supporting yourself well today.",
        "Your body seems settled. That's worth acknowledging.",
        "Main character posture. Fully earned.",
        "That's a sustainable setup for a long study block.",
        "Looking sharp.",
        "You're investing in long-term performance.",
        "Glowing AND well-aligned. The universe is taking notes.",
        "You woke up and chose alignment. Iconic.",
        "Comfort and productivity are teaming up.",
        "Casual but well-aligned. Ideal combination.",
        "That's a restorative position, not just a restful one.",
        "That's you choosing your long-term comfort over short-term convenience.",
        "Executive posture, executive output. The correlation is real.",
        "Your spine is in its healing era and it's beautiful.",
        "Your body is thriving right now. Don't let it slip.",
        "Great awareness.",
        "The grind is real. So is what you're doing right now for your body.",
        "That's a study position your spine approves of.",
        "No intervention needed. Just a note that you're doing well.",
        "You've built a strong posture habit and a strong career. Not a coincidence.",
        "Scrolling in good form. That's a win.",
        "That's a habit that will outlast the hustle.",
        "Well aligned.",
        "You're stacking good habits while everyone else is just stacking tasks.",
        "That's a posture that earns respect before a word is spoken.",
        "That's what listening to your body actually looks like.",
        "Your physical ease is supporting your mental ease.",
        "Comfortable and steady.",
        "Effortless alignment. The best kind.",
        "That's the posture of someone who has their life together, at least partially.",
        "You're making things easier on yourself.",
        "Looking calm and focused.",
        "The details separate good from great. This is one of those details.",
        "Your neck is living its best life and you did that.",
        "Looking focused and comfortable.",
        "Even on a brutal day, your posture is showing up.",
        "Your reading position just got a quiet stamp of approval.",
        "Your body is fully on board today.",
        "You're leading with your whole presence today.",
        "Solid posture for a casual session.",
        "Beautiful alignment. Keep going.",
        "Comfortable and correctly positioned. Keep it.",
        "Your back just got extra credit.",
        "Great positioning.",
        "Keep it up.",
        "Good posture habit in progress.",
        "That's the posture equivalent of a green flag.",
        "That's healthy studying.",
        "Another win for your body.",
        "Beautiful alignment.",
        "You found the sweet spot between relaxed and aligned. Stay there.",
        "Every detail of your presence is on right now.",
        "You're moving through the day without accumulating unnecessary strain.",
        "Nice work.",
        "Good form through the fatigue. Quietly impressive.",
        "Nice work maintaining alignment.",
        "Your back will be thanking you at 55. Seriously.",
        "You're reducing strain one moment at a time.",
        "Your body and your work are in alignment right now.",
        "Your spine is along for the ride comfortably.",
        "You've maintained alignment through a long scroll session. Noted.",
        "Posture check: passed with energy.",
        "That's a sustainable reading posture. The long sessions won't cost you.",
        "Cozy without compromise. That's the goal.",
        "Comfort and focus make a great team.",
        "Your body is in it with you today.",
        "That's the posture of someone who takes their leisure seriously.",
        "You're relaxed without being collapsed. That's the zone.",
        "Consistent. Calibrated. On point.",
        "Your back will still feel good when the chapter ends.",
        "Consistency looks good on you.",
        "That's the standard. You've set it. Now hold it.",
        "Well done staying connected to your posture.",
        "That's a healthier position.",
        "That's a healthy study habit forming in real time.",
        "Excellent alignment.",
        "Great consistency.",
        "Peak performance starts to look like this.",
        "You're not just grinding. You're grinding smart.",
        "What you're building here — in your posture and your work — is sustainable.",
        "Your focus and your form are both on right now.",
        "Grounded and present. That's a meaningful combination.",
        "Body and output both performing. That's rare. Protect it.",
        "That's what optimization looks like.",
        "That's executive-level physical discipline.",
        "Great posture. Keep the brainpower flowing.",
        "Your body is holding strong even when everything else is demanding more.",
        "You're building performance from the ground up.",
        "This looks sustainable.",
        "Your posture is part of your brand. Today it's an asset.",
        "That's the right way to do nothing in particular.",
        "Looking good.",
        "That's what high-standard physical discipline looks like in practice.",
        "Your body is in its healing era and it shows.",
        "Well-placed. Well-paced. Keep going.",
        "Keep that momentum going.",
        "Strong positioning.",
        "That's a posture that can last without effort.",
        "Peak operational posture. Maintain.",
        "That's the physical equivalent of a well-structured argument.",
        "Comfortable and supported.",
        "Small improvements add up.",
        "That posture is so good it almost makes up for everything else. Almost.",
        "Optimal spine position, optimal cognitive load distribution.",
        "Great alignment. Keep going.",
        "Spine straight. Standards high. That's the energy.",
        "Level head. Good habit.",
        "Strength in the spine. Strength in the room.",
        "That's the kind of physical discipline that keeps you in the game long-term.",
        "Small habits create big results.",
        "Studying smart and sitting smart. Rare combination.",
        "Maintain the advantage.",
        "Carry this into the rest of the day. It compounds.",
        "You hold yourself to a high bar. This proves it.",
        "Nice work. Your future self will thank you.",
        "That's a high-performance position.",
        "Your body is matching your output right now.",
        "Keep that standard high.",
        "That's a premium posture streak.",
        "You're not just building healthy habits. You're actually keeping them.",
        "Staying aligned.",
        "Looking strong through the stress.",
        "Excellent form.",
        "You've figured out how to be comfortable without being careless. Rare skill.",
        "Your posture is reflecting the calm you're cultivating.",
        "You're being gentle with yourself today. It shows.",
        "That's a posture streak hiding inside a scroll session.",
        "Your energy is protected. Your posture helped do that.",
        "Command starts with how you carry yourself. Nailed it.",
        "You showed up for yourself in a small way that adds up to something big.",
        "Aligned through a long haul. That's underrated toughness.",
        "Academic stress is manageable. Physical stress is optional. You chose correctly.",
        "You're operating efficiently.",
        "Nicely done.",
        "Your brain is working hard. Your body is finally cooperating.",
        "You're staying at your best.",
        "Looking sharp. Keep it going.",
        "You're reducing the physical toll of a demanding lifestyle, one correction at a time.",
        "One less thing going wrong today. Good.",
        "That's the kind of consistency that compounds.",
        "That's the posture of someone in control.",
        "Quiet, comfortable, aligned. All three.",
        "Nice work maintaining balance.",
        "Everything about this moment is well-chosen, including how you're sitting.",
        "Excellent positioning. Stay with it.",
        "Peak performance unlocked.",
        "Operating at full structural capacity. Carry on.",
        "That's the kind of discipline that doesn't show up on a CV but shows up everywhere else.",
        "You're making the semester harder on the content and easier on your body.",
        "That's a solid posture streak.",
        "You've maintained alignment through a demanding session. That's discipline.",
        "Alignment without effort is what happens after a long streak of good choices.",
        "That's aligned and that's intentional. Both matter.",
        "That's a habit worth keeping.",
        "Your body is working with you today, not against you.",
        "Great posture. Great presence.",
        "That's a posture streak you can build an exam block around.",
        "That's a win today.",
        "Keep nurturing that habit.",
        "You're doing the most (the right amount) for your body right now.",
        "You're holding yourself with quiet steadiness.",
        "Settled in well. Your back is happy inside the comfort.",
        "That's what studying without self-sabotage looks like.",
        "Keep doing what works.",
        "Nice work staying aligned.",
        "That's how you spend an afternoon without paying for it the next morning.",
        "That's a posture streak your future joints will celebrate.",
        "Phone up, shoulders down, all good.",
        "That's how you protect your neck without thinking about it.",
        "That's a physical boundary you set with yourself and kept.",
        "Sustained alignment is a form of self-leadership.",
        "Good posture maintained.",
        "You sat up straight and honestly that's the most attractive thing you've done today.",
        "Good posture detected. Superiority complex: justified.",
        "Your body called. You answered. That's a relationship worth maintaining.",
        "Nice work supporting your body.",
        "Great alignment.",
        "Soft life energy, strong spine. The combination is possible and you're proving it.",
        "Whole-body wellness includes this. You're doing it right.",
        "That's a posture that could last the whole study session.",
        "That's a lovely posture.",
        "Alignment looks great.",
        "Your body thanks you for this.",
        "Your body is an asset today, not an obstacle.",
        "Cozy and supported. That's the ideal state.",
        "Your neck is grateful and so is your focus.",
        "That's a healthy study habit.",
        "Your future self appreciates this.",
        "Another small win today.",
        "No wasted energy, no wasted positioning. Efficient.",
        "You're protecting your body in the middle of doing something purely for pleasure. Good instinct.",
        "Posture on track.",
        "Aligned spine. Aligned priorities.",
        "Your body is thanking you in a language you'll hear clearly in ten years.",
        "Looking strong today.",
        "That's a posture that closes deals.",
        "You're showing up strong today.",
        "That's mindful working made physical.",
        "That's a commanding position and you know it.",
        "You're creating space for comfort.",
        "Nice alignment.",
        "Your body appreciates this.",
        "You're investing in your future self and your future self is grateful.",
        "Nicely aligned.",
        "Looking relaxed and aligned.",
        "That's executive-level posture.",
        "Strong posture. Strong professional presence.",
        "That's a posture that matches the level of care you put into everything else.",
        "Studying smarter already.",
        "Your body is performing to the same standard as your work.",
        "That's executive-level alignment.",
        "Your body is resting while your mind is doing the work. That's the balance.",
        "A healthy habit is taking shape.",
        "Less tension in the neck, more bandwidth for the actual work.",
        "That posture just said \"I respect myself\" and honestly, same.",
        "Nicely balanced.",
        "Keep giving your body that support.",
        "Looking confident and composed.",
        "Looking balanced.",
        "Looking comfortable and supported.",
        "Easy on the neck. Easy on the scroll.",
        "You've created a reading environment that's kind to your body. That took thought.",
        "Good posture detected.",
        "You're taking care of the machine while running it hard.",
        "Well done.",
        "Excellent positioning.",
        "This is what high performance looks like from the inside.",
        "That's a posture worth keeping.",
        "Your back is thriving and so are we watching this.",
        "You're taking care of yourself.",
        "Good posture. One less thing to worry about.",
        "Physical infrastructure: optimal.",
        "Your posture is not adding to the problem. Rare and appreciated.",
        "Great balance.",
        "That's mindful working in action.",
        "Great job staying aligned.",
        "You're built different. Also your posture confirms this.",
        "Aligned. Composed. Prepared. All three simultaneously.",
        "Good posture doesn't always require effort. Today it didn't.",
        "Solid posture streak for someone who hasn't stopped moving.",
        "A lovely alignment in a lovely setting.",
        "You're doing your body a favor.",
    )

    val reminderMessages = listOf(
        "Time to show your spine some love! Try {exercise} \uD83D\uDCAA",
        "Your check-in is here \u2728 Keep the streak alive with a quick {exercise}!",
        "Bestie, your neck deserves a stretch. Try {exercise} \u2014 takes 30 secs \uD83E\uDDD8",
        "Just a gentle nudge \uD83C\uDF3F Try {exercise} and keep that posture score glowing.",
        "Your future self will thank you for this. Quick {exercise}? \uD83D\uDE4F",
        "Screen time check! Everything good? Try {exercise} while you're at it \uD83D\uDCF1",
        "The Slouch Monster hasn't shown up yet \uD83D\uDC4D Keep it that way with {exercise}!",
        "Periodic vibe check \uD83D\uDD2E Your posture looks good \u2014 but {exercise} makes it even better.",
        "Hey champion \uD83C\uDFC6 Quick {exercise} to keep that neck happy?",
        "Your spine called. It said try {exercise}. We don't make the rules \uD83E\uDD37",
        "You've been scrolling like a pro. Now stretch like one \u2014 try {exercise} \uD83D\uDE80",
        "Mini break time! {exercise} takes less time than choosing what to watch next \uD83D\uDCFA",
        "Plot twist: {exercise} is the main character today \uD83C\uDFAC",
        "Quick flex: try {exercise} and earn some posture points \uD83D\uDCAB",
        "Not to be dramatic, but {exercise} could change your whole vibe right now \u2728",
        "Your neck's daily dose of love: {exercise}. Takes 30 secs, feels amazing \uD83D\uDC96",
        "Time for your scheduled stretch break! {exercise} is calling \uD83D\uDCDE",
        "Still going strong! Try {exercise} to level up that streak \uD83D\uDD25",
        "Posture's looking good! Now make it legendary with {exercise} \uD83E\uDDB8",
        "Wellness moment \u2764\uFE0F Try {exercise} \u2014 your future neck thanks you.",
        "Small effort, big payoff. Give {exercise} a quick go \uD83C\uDFAF",
        "Your reminder to be kind to your body \uD83C\uDF3B Try {exercise}!",
        "Loading... {exercise}. Just kidding, you have to do it yourself \uD83D\uDE02",
        "Hey \uD83D\uDC4B Just checking in. Have you tried {exercise} today?",
        "In a world of scrolling, be the one who stretches. Try {exercise} \uD83C\uDF0D",
        "Think of {exercise} as a power-up for your spine \uD83C\uDF1F",
        "You + {exercise} = unstoppable posture energy \u26A1",
        "The algorithm says try {exercise}. (Okay, it's us. We say try it.) \uD83E\uDD16",
        "Your wellness check-in! Posture: solid. Next quest: {exercise} \uD83C\uDFAE",
        "Gentle reminder that {exercise} exists and your neck would appreciate it \uD83D\uDE0C"
    )
}
